# Generated by Django 4.2 on 2023-04-10 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_nacimiento',
            new_name='año_nacimiento',
        ),
    ]
