# Generated by Django 4.2 on 2023-04-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_fecha_nacimiento_paciente_año_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='año_nacimiento',
            field=models.IntegerField(),
        ),
    ]
