# Generated by Django 4.2 on 2023-05-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_paciente_dni_alter_paciente_año_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='index.html')),
            ],
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
